version: 1.0.{build}
image: Visual Studio 2019
build_script:
- cmd: git submodule update --init --recursive
- cmd: mkdir build && cd build
- cmd: cmake ..
- cmd: cmake --build . --config Release
artifacts:

- path: C:\projects\novmp\build\NoVmp\Release\NoVmp.exe
  name: NoVmp
